### ISSUE TITLE
visualviewportchanged event will be async

### ISSUE THREAD

**Issue by staktrace** [WICG/ViewportAPI#11]
The proposal suggests firing a visualviewportchanged event to content. With async panning/zooming, this event will necessarily be async and laggy, just like the scroll event. I don't really have any better ideas at the moment but I wanted to raise an issue for it as I think it merits further discussion. If authors start relying on this event to implement scroll-linked effects then it can result in bad-looking behaviour if the main thread is busy or under load.

**Comment by bokand** [comment]
Yes, the intention is that it's basically an analogue to onscroll today. Anyone who wants to do this is relying on even worse hacks today so this is already an improvement. I think this is similar to other parts of the platform where we expose the full flexibility to the main thread and provide "syntactic sugar" for common use cases that we run off thread. We just haven't provided the "sugar" yet. Letting web devs experiment with this should help inform us on what "sugar" we should be building. (position: device-fixed seems likely but who knows what else people might build).

**Comment by ymalik** [comment]
I think the main use of the visualviewportchanged event will probably be to position things relative to the visual viewport. Having used the API, its obvious that it's not the ideal way to move things around, but I agree that its far easier than what's currently available. 

There are probably other cases when its not that bad to have an async event. For example, hiding certain elements from the DOM when the user pinch zooms in. I wonder if it makes any sense to have an event that's fired when the user is done pinch-zooming. 

Also, note that the visualviewportchanged event has been split into scroll and resize events on visualViewport.

**Comment by bokand** [comment]
Closing since this is intentional.
