### ISSUE TITLE
Split visualviewportchanged into scroll/resize?

### ISSUE THREAD

**Issue by ChumpChief** [WICG/ViewportAPI#15]
Currently a visualviewportchanged listener will trigger on every scroll.  If a developer is really only interested in observing the size of the visual viewport, this would be more noisy than intended.

**Comment by bokand** [comment]
Just to clarify, it would only trigger on scrolls that move the visual viewport with respect to the layout viewport. i.e. scrolling when fully zoomed out wouldn't trigger this.

I think it would be easy enough for the author to filter the events based on what changed but a case could be made that this will be common enough to warrant separate events.

**Comment by bokand** [comment]
Hmm...perhaps instead of having `visualviewportchanged` we should just use the `scroll` and `resize` events but fire them against `window.visualViewport`. That seems more congruent with existing events. WDYT?

**Comment by bokand** [comment]
We've since replaced viewportchanged with the more common scroll/resize events.
