### ISSUE TITLE
Should scrollTop/Left be relative to document origin rather than layout viewport?

### ISSUE THREAD

**Issue by ChumpChief** [WICG/ViewportAPI#20]
And similarly, visualviewportchanged fire when the position changes relative to the document origin rather than just the layout viewport.

Arguments for document origin:

1.  Better matches the current behavior of pageXOffset/YOffset which these APIs are intended to supplant.
2.  Better matches scenarios involving triggers at particular scroll offsets -- e.g. load in more content when the visual viewport is at 95% of the scrollHeight.
3.  Better matches scenarios involving positioning of non-fixed content, e.g. absolute-positioned modal dialogs that should be centered in the visible region.
4.  Better matches scenarios of scrolling a particular part of the document into view by setting visualViewport.scrollTop
5.  visualviewportchanged is sufficient to detect visual viewport motion relative to the document -- the developer doesn't need to additionally register for the scroll event

Arguments for layout viewport origin:

1.  Better matches scenarios involving positioning of fixed content, e.g. pseudo-device-fixed as your code sample demonstrates.
2.  Better matches "is in view" checks since the offsets can be directly compared against the getBoundingClientRect() of the target, which is also measured relative to the layout viewport origin.
3.  visualviewportchanged can fire more rarely, particularly in usage scenarios with prolonged panning against the edge of the layout viewport.

I lean towards document origin but can see the pros for each side.  I'm guessing you may have had additional reasoning for selecting layout viewport origin in your draft -- anything I'm missing above?

**Comment by bokand** [comment]
I think the layout viewport origin is a better explanation for what's actually going on under-the-hood, the layout viewport is the scrolling content of the visual viewport. The document origin might be more convenient in some cases but I think it'll obfuscate the relationship of the two viewports.

More practically, using document-origin means that we then have to make choices about which viewport to scroll first when the developer writes to these properties. I think there are arguments for scrolling layout first and visual first in different scenarios. Without including the layout-origin coodinates the author has no way to choose.

I would rather we provide a utility somewhere to convert to document-origin or just include a polyfill since it's quite easy to go to document-origin from layout-origin.

**Comment by bokand** [comment]
We've been working on a polyfill and some examples and one of my findings working with this is that getting the properties of the layout viewport across browsers is not straightforward.

To get the layout viewport dimensions you need to:
Add a `position: fixed; height:100%; width: 100%` invisible element to the page and use `getBoundingClientRect()` to get its size.

To get the layout viewport scroll offset you need to:
Add a `position: absolute; left: 0px; top: 0px;` element and use `getBoundingClientRect` to get the _negative_ of the layout viewport scroll offset.

This is somewhat clunky, though it works in Chrome/Edge/Firefox (working on Safari now). For that reason, I think I now agree that having document-relative coordinates in visualViewport is a good idea. It lets authors position elements using position: absolute without worrying about the layout viewport. For the reason I mention above, I think they should be read-only.

IMO, we should also keep `scrollTop` and `scrollLeft` relative to the layout viewport and keep those writable. In addition to being writable, I've found simulating position: device-fixed using a position: fixed element to be much smoother than position: absolute; when you're fully zoomed out, it looks perfect and you only get a bit of delay jank when you zoom in.

So, what do you think about adding `visualViewport.pageX` and `visualViewport.pageY`?

**Comment by bokand** [comment]
pageX/pageY should be in the latest canary and they've been added to the draft spec.
