### ISSUE TITLE
Polyfill calculation of scale is incorrect

### ISSUE THREAD

**Issue by ChumpChief** [WICG/ViewportAPI#21]
outerWidth is not a safe property to use in polyfills since its value varies per each UA's browser chrome.  This calculation is wrong on all non-maximized desktop browsers as a result.

**Comment by bokand** [comment]
Thanks, didn't realize outerWidth/Height includes the window shadow on Windows :P

Took a bit of ingenuity and hacks but I think the updated method if pretty robust.
