### ISSUE TITLE
Polyfill calculation of clientWidth/Height uses magic number 15

### ISSUE THREAD

**Issue by ChumpChief** [WICG/ViewportAPI#22]
I think this is maybe supposed to represent the scrollbar width?  If so then it will be incorrect at scale values other than 1.0 (since the scrollbar doesn't scale as the user zooms) and also incorrect for any UAs with scrollbars of differing widths.

**Comment by bokand** [comment]
Yah, that was temporary. The latest version looks like it accounts for scrollbars correctly in my testing.
