### ISSUE TITLE
Use Case: Scaling of Bitmap Data

### ISSUE THREAD

**Issue by Helmut-Emmelmann** [WICG/ViewportAPI#23]
I am experimenting with visualViewport.scale to detect the best resolution needed for bitmap elements (e.g. image or canvas). Currently I multiply the CSS pixel size of an HTML canvas by the factor (visualViewport.scale*window.devicePixelRatio). This accounts for pinch zoom, browser zoom, and physical device pixel ratio. window.devicePixelRatio already contains the physical device pixel ratio multiplied by the browser zoom factor and visualViewport.scale accounts for the pinch zoom. This part works fine on Chrome Canary Win 8.1.

I also use window.innerWidth in order to limit the size of a WebGL canvas (which is an important performance optimization) to the part of the canvas that is actually visible. I tried to replace window.innerWidth by visualViewport.clientWidth, however it turns out that visualViewport.clientWidth is a bit smaller than window.innerWidth (according to the old semantics, i.e. with disabled inert-visual-viewport), which probably accounts for the space of the scroll bar. When pinch zooming-in this difference seems to stay constant and does not scale with the pinch zoom. (Tested emulating a laptop with touch in developer tools on windows 8.1, 54.0.2820.0  canary, enabled enable-experimental-web-platform-features and disabled inert-visual-viewport).

The fixed-to-keyboard.html seems to experience this problem as well: Add a horizontal scroll bar below the red box, (e.g. by increasing the width of the text area in the elements panel of developer tools). Then pinch zooming-in makes the red box move up and no longer stay directly on top of the scroll bar. (Tested emulating a laptop with touch in developer tools on windows 8.1, 54.0.2821.0  canary, enabled enable-experimental-web-platform-features and enabled inert-visual-viewport).

**Comment by ymalik** [comment]
Yes, the difference between visualViewpot.clientWidth and window.innerWidth (without the inert-visual-viewport flag) is that the former excludes the width of the vertical scrollbar. 

I believe the problem you mentioned with fixed-to-keyboard.html is filed as crbug.com/634424, and will be fixed before we ship the viewport api.

**Comment by bokand** [comment]
The bug referenced by @ymalik above has been fixed.

Could you confirm that the way clientWidth works is preferred in your use case? i.e. presumably you want the width without including the scrollbar so that the scrollbar doesn't overlay the canvas, right? Or am I misunderstanding and you'd prefer if clientWidth worked like innerWidth and included the scrollbar? This is being considered in #19

**Comment by bokand** [comment]
I'm also going to close this as I'm trying to keep the list down to actionable issues but this is very valuable so thanks for filing (and file more use cases if you have them)!
