### ISSUE TITLE
When events fire should match the latest CSSOM View spec

### ISSUE THREAD

**Issue by zcorpan** [WICG/ViewportAPI#25]
See https://drafts.csswg.org/cssom-view/#events

I could add some hook or something to CSSOM View for this if that would help.

**Comment by bokand** [comment]
Should I just copy this into my spec or is linking to it enough? I currently link to the existing WD.

**Comment by zcorpan** [comment]
Linking works I suppose. Eventually this spec should probably be merged into cssom-view if it's widely implemented. 😊

**Comment by bokand** [comment]
Thanks, agreed it would probably belong in cssom-view eventually. I've updated the links to point to your ED for now.

**Comment by jakearchibald** [comment]
> These events follow the procedure defined in section 12.1 of the CSSOM View module.

I didn't really know what this meant until I stumbled across this issue.

It'd be great if the spec could be more specific about how it interacts with CSSOM. For example:

These steps should happen as part of [run the resize steps](https://drafts.csswg.org/cssom-view/#run-the-resize-steps), after the existing steps:
