### ISSUE TITLE
visualViewport should probably be [SameObject, Replaceable]

### ISSUE THREAD

**Issue by zcorpan** [WICG/ViewportAPI#26]
New things on window typically need to be annotated with `[Replaceable]`.  The attributes CSSOM View defines on window are, https://drafts.csswg.org/cssom-view/#extensions-to-the-window-interface

Also you could add `[SameObject]` to require that the same object is returned every time.

So
```
partial interface Window {
    [SameObject, Replaceable] readonly attribute VisualViewport visualViewport;
};
```

**Comment by bokand** [comment]
Thanks, fixed now.
