### ISSUE TITLE
scrollTop, scrollLeft, pageX, and pageY should be clearer about units

### ISSUE THREAD

**Issue by dbaron** [WICG/ViewportAPI#28]
The [definitions](https://rawgit.com/WICG/ViewportAPI/master/index.html#the-visualviewport-interface) of <code>scrollTop</code>, <code>scrollLeft</code>, <code>pageX</code>, and <code>pageY</code> don't say anything about what units they're in.  It seems like they should.  (Similar properties [in cssom-view](https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface) should too!)

Noticed while reviewing the spec for https://github.com/w3ctag/spec-reviews/issues/128

**Comment by ymalik** [comment]
This is resolved in https://github.com/WICG/ViewportAPI/commit/4b7d4b584f896588aa554611ef36af38ec23c853
