### ISSUE TITLE
definition of scroll event should be clearer about what constitutes a scroll

### ISSUE THREAD

**Issue by dbaron** [WICG/ViewportAPI#30]
The [definition](https://rawgit.com/WICG/ViewportAPI/master/index.html#events) of the scroll and resize events should be clearer about when, exactly, the scroll event is fired.

In particular, a resize, by definition, changes *some* edges of the visual viewport.  Does the scroll event fire at the same time as a resize event if the resize involves a change to certain edges (the top or left, or something dependent on directionality?) of the viewport, does a scroll event always also fire along with a resize event, or does a scroll event never fire at the same time as a resize event since a resize event implicitly changes some of the edges of the visual viewport?

**Comment by dbaron** [comment]
Oh, and I got here from https://github.com/w3ctag/spec-reviews/issues/128

**Comment by ymalik** [comment]
Resolved in https://github.com/WICG/ViewportAPI/commit/4580568d06a71611222c3464e7afe0faf71e498a.
