### ISSUE TITLE
resize/scroll events on visualviewport are underspecified

### ISSUE THREAD

**Issue by staktrace** [WICG/ViewportAPI#37]
The draft spec says e.g. "The user agent must fire an Event named resize on the window.visualViewport object" - but it doesn't provide any details about this event. Does it bubble up to the window? Is it cancelable? Does it have any relatedTarget elements or anything of that nature? Does it extend from `UIEvent` or `Event`?

**Comment by staktrace** [comment]
(I realize that there is a link to CSSOM-View but it's not obvious how to map what that spec says about those events to this spec).

**Comment by cvrebert** [comment]
Using the ["fire an event named"](https://dom.spec.whatwg.org/#concept-event-fire) algorithm from DOM would reduce ambiguity.

**Comment by bokand** [comment]
Thanks for the tip @cvrebert, we've used that to clarify and I've added a bit more detail. @staktrace is [it ok now](https://wicg.github.io/ViewportAPI/spec.html#events)?

**Comment by staktrace** [comment]
@bokand yup, thanks!
