### ISSUE TITLE
Definition of scale is not clear

### ISSUE THREAD

**Issue by staktrace** [WICG/ViewportAPI#38]
The definition provided for the `scale` property is not fully clear to me. That's probably because terms like "device pixel" are not well-defined specially when dealing with things like retina displays and automatic OS-level pixel doubling. An example scenario with both pinch-zoom and browser zoom applied would also help clarify the "note".

**Comment by bokand** [comment]
@staktrace I've updated the definition to be hopefully more clear, WDYT?

**Comment by staktrace** [comment]
@bokand that is much clearer, thanks!
