### ISSUE TITLE
Please don't call it "viewport"

### ISSUE THREAD

**Issue by johnmellor** [WICG/ViewportAPI#4]
Everywhere else on the web platform, viewport means (or will soon mean) the layout viewport. For example:

- meta viewport
- CSS @viewport
- CSS vw,vh units
- throughout the CSSOM View module

So it would be very confusing for `document.viewport` to mean something different. People will try to use `document.viewport.clientWidth` to get the layout viewport width, etc.

Whilst the Chrome team internally uses terminology like layout viewport and visual viewport, and understands the difference, many web developers don't know there are two viewports.

Instead how about:

- document.visibleArea
- document.visibleRect
- document.visualViewport
- document.zoomRect
- document.zoomViewport
- document.zoomArea

**Comment by bokand** [comment]
You're right, I was trying to be succinct but this is potentially confusing.

I'm sure there'll be plenty of bikeshedding about this when we start talking specification but for now I've changed it to visualViewport. Us and the Edge team have been using this terminology and I've seen it used by web devs too so we might as well bake it in.
