### ISSUE TITLE
Demo link doesn't work

### ISSUE THREAD

**Issue by staktrace** [WICG/ViewportAPI#40]
The demo thingy at http://bokan.ca/viewport/index.html was super useful, but going there now triggers a page download in Firefox instead of just loading it. Maybe it's being served with the wrong content-type or content-disposition?

**Comment by bokand** [comment]
Dropbox discontinued HTTP serving so I've moved it to http://bokand.github.io/viewport/index.html.
I've updated the link in the README, thanks for the heads up.
