### ISSUE TITLE
Should visualViewport be on `window` rather than `document`?

### ISSUE THREAD

**Issue by bokand** [WICG/ViewportAPI#7]
It seems to be more conceptually appropriate under `window` and this is some of the common feedback I've heard. The reason we avoided window was to avoid clashing with the app's namespace but maybe this fear is overblown?

**Comment by ChumpChief** [comment]
Or on the document.scrollingElement?

**Comment by bokand** [comment]
That was basically where I had it originally but got some feedback in issue #1 as to why that's not a great idea. Basically, it would require extending the interface for Element just to get a property on one object.

I've done a search through the HTTPArchive and found no conflicting uses at all with `visualViewport` so I think putting it on `window` shouldn't be a problem and is least surprising to web devs.

**Comment by ChumpChief** [comment]
Any of the above sound fine to me for now, no strong preference.

**Comment by bokand** [comment]
I've updated Chrome's implementation and the explainer to use `window.visualViewport` so I'm marking this closed.
