### ISSUE TITLE
Use `zoom` instead of `scale`

### ISSUE THREAD

**Issue by bokand** [WICG/ViewportAPI#8]
This terminology is more in line with what web devs use. `Scale` is what we've used internally to distinguish browser and pinch zooms and it leaked out here. Perhaps having it on the visual viewport is distinguishing enough?

**Comment by bokand** [comment]
On the other hand, `scale` is good because it's consistent with the viewport `<meta>` tag.

**Comment by ymalik** [comment]
Currently, the spec has `pageScale`. Some names that we have discussed are: `scale`, `zoom`, `zoomFactor`, `layoutVisualRatio`. I think `scale

**Comment by bokand** [comment]
We've settled on `scale` for now. This lets us differentiate from ctrl+/- and makes the connection to the `scale` properties of `viewport <meta>` clear.
